appname:            'BaNG'
layout:             'main'
server:             '0.0.0.0'
template:           'template_toolkit'
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '<%'
    end_tag:   '%>'
show_errors:        1
error_template:     'error'
default_mime_type:  'text/plain'
logger:             'file'
logger_format:      '%t [%L] %m'
log_path:           '/opt/BaNG/var/log'
session:            'YAML'
session_dir:        '/opt/BaNG/var/sessions'
admin_role:         'BaNG-admin'
plugins:
  Auth::Extensible:
    no_default_pages: 1
    no_login_handler: 1
    realms:
      config:
        provider:   'Config'
        users:
          - user:   'admin'
            pass:   'supersecret'
            cn:     'Admin User'
            roles:
              -     'BaNG-admin'
          - user:   'guest'
            pass:   'guest'
            cn:     'Guest User'
     #ldap:
     #  provider:   'LDAPphys'
     #  server:     'ldap.example.com'
     #  base_dn:    'ou=Company,o=example,c=com'
     #  group_filter: '(objectClass=groupclass)'
